### ISSUE TITLE
Add Full Support for Localization

### ISSUE THREAD

**Issue by bwendlandt-intel** [device-management-toolkit/sample-web-ui#2124]
# 🏆 **Hackathon Task: Enable i18n Support**

## 🔹 Overview
The `sample-web-ui` project currently lacks **internationalization (i18n) support**. To ensure scalability and ease of adding multiple languages in the future, we will first enable **i18n** in Angular **19** and configure **English (en-US) as the default language**. 

This first step will focus on **titles and headers**.  Feel free to add subsequent PRs that will add additional translations beyond titles and headers.

## 🎯 **Task Scope**
- [ ] **Step 1:** Enable Angular's **i18n** support in the project.
- [ ] **Step 2:** Configure English (`en-US`) as the default language.
- [ ] **Step 3:** Use **translation files** (e.g., `assets/i18n/en.json`) for managing translations.
- [ ] **Step 4:** Replace hardcoded titles and headers with translation IDs (avoid Angular’s autogenerated IDs).
- [ ] **Step 5:** Implement **a structured naming convention** for translation IDs (e.g., `header.title`, `nav.home`).
- [ ] **(Optional, if time allows)** Consider [ng-extract-i18n-merge](https://www.npmjs.com/package/ng-extract-i18n-merge) for managing the lifecycle of new additions.

## 📂 **Relevant Files**
- `src/assets/i18n/en.json` (to be created)
- `src/app/app.component.html`
- `src/app/shared/components/` (update relevant components)
- `angular.json` (to configure i18n settings)

## 💻 **Technical Details**
- Use **Angular’s built-in i18n** (https://angular.dev/guide/i18n/add-package#)
- **Use translation IDs & descriptions**, avoiding Angular’s autogenerated IDs, here is an example:
  ```json
  {
    "header.title": {
      "value": "Sample Web UI",
      "description": "Main title of the application"
    },
    "nav.home": {
      "value": "Home",
      "description": "Navigation label for the home page"
    }
  }

**Comment by DanielMoya-Intel** [comment]
OpenAMT_Team1 from Intel Hackathon will be taking this issue
